# Generated by Django 4.2.13 on 2024-06-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.URLField(blank=True, default='https://via.placeholder.com/300', max_length=300, null=True),
        ),
    ]
