# Generated by Django 4.2.13 on 2025-08-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_remove_cart_items_remove_cartitem_user_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='Unnamed', max_length=100),
            preserve_default=False,
        ),
    ]
