# Generated by Django 4.2.27 on 2025-12-19 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='Unnamed', max_length=100),
        ),
    ]
